[package]
name = "dverify"
version = "1.0.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
log = "0.4.25"
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.137"
sha2 = "0.10.8"
structopt = "0.3.26"
thiserror = "2.0.11"
